version: '3.8'

services:
  quantalert:
    build: .
    container_name: quantalertsystem
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DEFAULT_SYMBOLS=${DEFAULT_SYMBOLS:-AAPL,GOOGL,MSFT,TSLA,NVDA}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_PATH=/app/data/quant_alerts.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "-m", "quantalertsystem.main", "--no-alerts"]
    
  # Optional: Run periodic analysis with cron-like scheduling
  quantalert-scheduler:
    build: .
    container_name: quantalertsystem-scheduler
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - DEFAULT_SYMBOLS=${DEFAULT_SYMBOLS:-AAPL,GOOGL,MSFT,TSLA,NVDA}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - DATABASE_PATH=/app/data/quant_alerts.db
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
    command: |
      sh -c "
      while true; do
        echo 'Running market analysis...'
        python -m quantalertsystem.main
        echo 'Sleeping for 4 hours...'
        sleep 14400
      done
      "
    profiles:
      - scheduler